apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs
spec:
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      containers:
      - name: srs
        image: simple-rest-server:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: srs
spec:
  selector:
    app: srs
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
